// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiD6nzrNs3isViCzhL4sRpLCvhnmb9K2o',
    appId: '1:740371333070:web:e1c1cda3b474c0c370b59f',
    messagingSenderId: '740371333070',
    projectId: 'flex-fit-f31cd',
    authDomain: 'flex-fit-f31cd.firebaseapp.com',
    storageBucket: 'flex-fit-f31cd.appspot.com',
    measurementId: 'G-36NHHYFD2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCORcLL9ebXYN5VUtxL6xmfHxlchXuztww',
    appId: '1:740371333070:android:d67fbe85353137cc70b59f',
    messagingSenderId: '740371333070',
    projectId: 'flex-fit-f31cd',
    storageBucket: 'flex-fit-f31cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA72DgDs3QJ4PDmvazfMeUOrAy_x9DEgHY',
    appId: '1:740371333070:ios:62ed17b19f5faf5970b59f',
    messagingSenderId: '740371333070',
    projectId: 'flex-fit-f31cd',
    storageBucket: 'flex-fit-f31cd.appspot.com',
    iosClientId: '740371333070-n3v3erroo5180vihk978i0jfruqb9qu9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flexFit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA72DgDs3QJ4PDmvazfMeUOrAy_x9DEgHY',
    appId: '1:740371333070:ios:64fa7ebbbfabb28370b59f',
    messagingSenderId: '740371333070',
    projectId: 'flex-fit-f31cd',
    storageBucket: 'flex-fit-f31cd.appspot.com',
    iosClientId: '740371333070-0akd08643jb5urn9nsuqn0mt8g98nbn0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flexFit.RunnerTests',
  );
}
